### ISSUE TITLE
Problem with zabbix_client and staticfilecache

### ISSUE THREAD

**Issue by secured** [svewap/zabbix_client#9] opened 2020-01-08 08:24 UTC
If the well known extension "staticfilecache" (https://github.com/lochmueller/staticfilecache) is used together with the zabbix_client extension an error is thrown inside TYPO3.

Core: Exception handler (WEB: Uncaught TYPO3 Exception: Call to a member function isStaticCacheble() on null | Error thrown in file .../ext/staticfilecache/Classes/Cache/Rule/StaticCacheable.php in line 32. Requested URL: .../zabbixclient/?operation=PageSpeedInsights_GetDegradedPageUids&strategy=desktop&field=seo_score

**Comment by fritzdacat** [comment] 2020-11-25 12:34
Could it be that the problem only occurs when the PageSpeedInsights extension is used together with the Zabbix extension?

**Comment by svewap** [comment] 2020-11-25 12:40
I speculate that the problem is the static file cache extension. Its very rudimentary mod rewrite rules can't distinguish whether the link is an API call or a page. 
So you just have to find out which exception you have to write in the htaccess file to make it work.

**Comment by fritzdacat** [comment] 2020-11-25 13:29
Seems to work that way too. But I haven't installed this PageSpeed Extension either.

**Comment by svewap** [comment] 2024-04-20 19:27
closing this issue. If there are still problems, please open again

**Closed as completed by svewap** 2024-04-20 19:27 UTC
